
title: zpallin

#------------------------------------------------------------------------------- 
# contact
email: zpallin@gmail.com
twitter_username: ZeppelinWS
github_username:  zpallin
image: https://avatars0.githubusercontent.com/u/2293721?v=4&s=460

description: > # this means to ignore newlines until "baseurl:"
  I'm a musician, bicyclist, motorcyclist, traveler, casual writer, gamer, 
  hiker, activist, and socializer. In my free time, I  build IT things with code 
  and do Ops stuff. San Jose, CA is my home.

#------------------------------------------------------------------------------- 
# site config
baseurl: ""
url: "https://zpallin.github.io"

#------------------------------------------------------------------------------- 
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll/tagging
exclude:
  - Gemfile
  - Gemfile.lock

#------------------------------------------------------------------------------- 
# tag settings
tag_page_layout: tag
tag_page_dir: blog/tags
